INSERT INTO DOCTOR_TYPE(DOCTOR_TYPE_ID, DOCTOR_TYPE_CODE, DOCTOR_TYPE_NAME, DOCTOR_TYPE_DURATION_MIN, DOCTOR_TYPE_DURATION_MAX, DOCTOR_TYPE_OVERLAPPING_APPOINTMENTS)
VALUES (101,'1', 'General', 5, 15, 2);
INSERT INTO DOCTOR_TYPE(DOCTOR_TYPE_ID, DOCTOR_TYPE_CODE, DOCTOR_TYPE_NAME, DOCTOR_TYPE_DURATION_MIN, DOCTOR_TYPE_DURATION_MAX, DOCTOR_TYPE_OVERLAPPING_APPOINTMENTS)
VALUES (102, '2', 'Specialist', 10, 30, 3);
INSERT INTO DOCTOR_TYPE(DOCTOR_TYPE_ID, DOCTOR_TYPE_CODE, DOCTOR_TYPE_NAME, DOCTOR_TYPE_DURATION_MIN, DOCTOR_TYPE_DURATION_MAX, DOCTOR_TYPE_OVERLAPPING_APPOINTMENTS)
VALUES (128, '3', 'Super Specialist', 20, 60, 4);
INSERT INTO DOCTOR(DOCTOR_ID, DOCTOR_NAME, DOCTOR_TYPE_ID, DOCTOR_EMAIL) VALUES (103, 'Mohammad Rezaie', 101, 'behnaz.mardanzadeh@gmail.com');
INSERT INTO DOCTOR(DOCTOR_ID, DOCTOR_NAME, DOCTOR_TYPE_ID, DOCTOR_EMAIL) VALUES (104, 'Mehrnoosh Vafaie', 102, 'behnaz.mardanzadeh@gmail.com');
INSERT INTO DOCTOR(DOCTOR_ID, DOCTOR_NAME, DOCTOR_TYPE_ID, DOCTOR_EMAIL) VALUES (105, 'Kian Ghanbari', 101, 'behnaz.mardanzadeh@gmail.com');
INSERT INTO DOCTOR(DOCTOR_ID, DOCTOR_NAME, DOCTOR_TYPE_ID, DOCTOR_EMAIL) VALUES (106, 'Mozhdeh Mozhdegani', 101, 'behnaz.mardanzadeh@gmail.com');
INSERT INTO DOCTOR(DOCTOR_ID, DOCTOR_NAME, DOCTOR_TYPE_ID, DOCTOR_EMAIL) VALUES (129, 'Nader Ghanbari', 128, 'behnaz.mardanzadeh@gmail.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (107, 'Karim Saghir', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (108, 'Matin Nazif', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (109, 'Rasa Koosha', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (110, 'Homa Pooya', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (111, 'Ali Khakzad', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (112, 'Shima Shayan', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (113, 'Nima Noori', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (114, 'Saba Sana', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (115, 'Negar Yari', 'yekta_hatami@yahoo.com');
INSERT INTO PATIENT(PATIENT_ID, PATIENT_NAME, PATIENT_EMAIL) VALUES (126, 'Mahsa Hoori', 'yekta_hatami@yahoo.com');
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (116, TO_TIMESTAMP('2023-07-19 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 11:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (117, TO_TIMESTAMP('2023-07-19 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (118, TO_TIMESTAMP('2023-07-19 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (119, TO_TIMESTAMP('2023-07-19 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 13:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (120, TO_TIMESTAMP('2023-07-19 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (121, TO_TIMESTAMP('2023-07-19 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 17:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (122, TO_TIMESTAMP('2023-07-19 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 16:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_DETAIL(SCHEDULE_DETAIL_ID, SCHEDULE_DATE_TIME_START, SCHEDULE_DATE_TIME_END) VALUES (127, TO_TIMESTAMP('2023-07-19 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE(SCHEDULE_ID, DOCTOR_ID, SCHEDULE_START_DATE, SCHEDULE_END_DATE) VALUES (123, 103, TO_TIMESTAMP('2023-07-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
UPDATE SCHEDULE_DETAIL SET SCHEDULE_ID = 123 WHERE SCHEDULE_DETAIL_ID in (116, 118, 127);
INSERT INTO SCHEDULE(SCHEDULE_ID, DOCTOR_ID, SCHEDULE_START_DATE, SCHEDULE_END_DATE) VALUES (124, 104, TO_TIMESTAMP('2023-07-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
UPDATE SCHEDULE_DETAIL SET SCHEDULE_ID = 124 WHERE SCHEDULE_DETAIL_ID in (117);
INSERT INTO SCHEDULE(SCHEDULE_ID, DOCTOR_ID, SCHEDULE_START_DATE, SCHEDULE_END_DATE) VALUES (125, 105, TO_TIMESTAMP('2023-07-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
UPDATE SCHEDULE_DETAIL SET SCHEDULE_ID = 125 WHERE SCHEDULE_DETAIL_ID in (119, 121);
INSERT INTO SCHEDULE(SCHEDULE_ID, DOCTOR_ID, SCHEDULE_START_DATE, SCHEDULE_END_DATE) VALUES (130, 129, TO_TIMESTAMP('2023-07-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-07-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
UPDATE SCHEDULE_DETAIL SET SCHEDULE_ID = 130 WHERE SCHEDULE_DETAIL_ID in (120);